### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by rainleander** [rainleander/insecure-api-project#1]
% curl -v -H "Content-Type: application/json" -d '{"username":"admin", "password":"password"}' http://localhost:5001/login

*   Trying 127.0.0.1:5001...
* Connected to localhost (127.0.0.1) port 5001 (#0)
> POST /login HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 43
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

**Comment by rainleander** [comment]
Simplified API which circumvents this issue.

**Comment by benarent** [comment]
I was able to get it running by setting the host. 

```diff
if __name__ == '__main__':
-    app.run(debug=True, port=8080)
+    app.run(host='0.0.0.0', debug=True, port=8080)
```

**Comment by rainleander** [comment]
This fixed the other issue as well! Thx @benarent
